/**
 * @file tools/host_sim/main.c
 * @brief Native harness that runs the VM with a stdout renderer.
 *
 * Because src/vn.c and src/text.c avoid calculator headers, they compile
 * unchanged on the host. This gives us a regression check for the bytecode
 * and the word wrapper without needing CEmu or hardware -- and later, a way
 * to replay every converted chapter looking for unknown opcodes.
 *
 * Modes:
 *   (default)   auto-play the compiled-in demo script, always taking menu option 0
 *   --vnb FILE  replay a real compiled chunk (tools/vnasm.py's
 *               Assembler.to_chunk_bytes() container -- see docs/FORMAT.md's
 *               "Chunking" section) instead of the demo script
 *   --pc=N      start execution at byte offset N instead of 0 -- a combined
 *               multi-file chunk's actual entry point (Ren'Py's `label
 *               start`) usually isn't at offset 0, since compile_script.py
 *               emits files in the order they were given, not by role
 *   --choices=  comma-separated menu picks, e.g. --choices=0,1,2,3
 *   --trace     also print SCENE/SHOW/HIDE state changes
 */

#include "../../src/demo.h"
#include "../../src/text.h"
#include "../../src/vn.h"

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define WRAP_COLS 64

static bool     opt_trace;
static unsigned choices[64];
static unsigned choice_count;
static unsigned choice_pos;

/* Set when --vnb loads a real chunk, so host_string() reads from it instead
 * of the compiled-in demo_strings[]. */
static char   **vnb_strings;
static uint16_t vnb_string_count;
static unsigned say_count;
static unsigned menu_count;

/* One "pixel" per character, so wrapping is measured in columns. */
static unsigned measure(void *ctx, const char *str, size_t len)
{
    (void)ctx;
    (void)str;
    return (unsigned)len;
}

static const char *speaker_name(uint8_t speaker)
{
    static const char *const names[] = { "Sayori", "Natsuki", "Yuri", "Monika" };

    if (speaker == VN_SPEAKER_NONE ||
        speaker >= sizeof(names) / sizeof(names[0])) {
        return NULL;
    }
    return names[speaker];
}

static const char *host_string(void *ctx, uint16_t index)
{
    (void)ctx;
    if (vnb_strings != NULL) {
        return index < vnb_string_count ? vnb_strings[index] : "";
    }
    return index < demo_string_count ? demo_strings[index] : "";
}

static void host_say(void *ctx, const vn_scene_t *scene)
{
    (void)ctx;
    say_count++;

    const char *name = speaker_name(scene->speaker);
    printf("%s\n", name ? name : "(narration)");

    /* Run the real wrapper so its output is part of what we verify. */
    text_layout_t layout;
    text_wrap(&layout, scene->text, WRAP_COLS, measure, NULL);

    for (uint8_t i = 0; i < layout.count; i++) {
        printf("  | %.*s\n", (int)layout.lines[i].len, layout.lines[i].start);
    }

    /* The dialogue box holds TEXT_MAX_LINES; anything past that would be
     * silently cut on-calc, so surface it here instead. */
    size_t consumed = 0;
    for (uint8_t i = 0; i < layout.count; i++) {
        consumed += layout.lines[i].len;
    }
    if (consumed + layout.count < strlen(scene->text)) {
        printf("  ! WARNING: line overflows %d display lines\n", TEXT_MAX_LINES);
    }
    printf("\n");
}

static uint8_t host_menu(void *ctx, const vn_scene_t *scene,
                         const char *const *options, uint8_t count)
{
    (void)ctx;
    (void)scene;
    menu_count++;

    unsigned picked = 0;
    if (choice_pos < choice_count) {
        picked = choices[choice_pos++];
        if (picked >= count) {
            picked = 0;
        }
    }

    printf("MENU:\n");
    for (uint8_t i = 0; i < count; i++) {
        printf("  %c %u) %s\n", i == picked ? '>' : ' ', i, options[i]);
    }
    printf("\n");

    return (uint8_t)picked;
}

static void host_update(void *ctx, const vn_scene_t *scene, uint8_t trans)
{
    (void)ctx;

    if (!opt_trace) {
        return;
    }

    printf("[scene bg=%u trans=%u actors=", scene->background, trans);
    for (int i = 0; i < VN_MAX_CHARS; i++) {
        if (scene->actors[i].character != VN_NO_SPRITE) {
            printf("{ch=%u sprite=%u pos=%u}",
                   scene->actors[i].character, scene->actors[i].sprite,
                   scene->actors[i].pos);
        }
    }
    printf("]\n");
}

static void host_pause(void *ctx, uint8_t frames)
{
    (void)ctx;
    if (opt_trace) {
        printf("[pause %u]\n", frames);
    }
}

static bool host_quit(void *ctx)
{
    (void)ctx;

    /* An infinite loop in generated bytecode would otherwise hang the build,
     * so cap the run rather than trusting the script to terminate. */
    return say_count > 10000;
}

static const vn_host_t host = {
    .string = host_string,
    .say    = host_say,
    .menu   = host_menu,
    .update = host_update,
    .pause  = host_pause,
    .quit   = host_quit,
    .ctx    = NULL,
};

static void parse_choices(const char *arg)
{
    const char *p = arg;

    while (*p != '\0' && choice_count < sizeof(choices) / sizeof(choices[0])) {
        char *end;
        unsigned long v = strtoul(p, &end, 10);
        if (end == p) {
            break;
        }
        choices[choice_count++] = (unsigned)v;
        p = (*end == ',') ? end + 1 : end;
    }
}

static uint16_t read_u16le(const uint8_t *p)
{
    return (uint16_t)(p[0] | (p[1] << 8));
}

/**
 * Load a tools/vnasm.py Assembler.to_chunk_bytes() container (see
 * docs/FORMAT.md's "Chunking" section): u16 code_length, code bytes, u16
 * string_count, then per string a u16 byte_length + UTF-8 bytes.
 *
 * Leaks its allocations deliberately -- this is a short-lived CLI replay
 * tool, not the on-calc loader.
 */
static bool load_vnb(const char *path, const uint8_t **code_out, size_t *code_size_out)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        fprintf(stderr, "cannot open %s\n", path);
        return false;
    }

    fseek(f, 0, SEEK_END);
    long total = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (total < 4) {
        fprintf(stderr, "%s: too small to be a chunk container\n", path);
        fclose(f);
        return false;
    }

    uint8_t *buf = malloc((size_t)total);
    if (fread(buf, 1, (size_t)total, f) != (size_t)total) {
        fprintf(stderr, "%s: short read\n", path);
        fclose(f);
        return false;
    }
    fclose(f);

    size_t pos = 0;
    uint16_t code_len = read_u16le(buf + pos);
    pos += 2;
    if (pos + code_len + 2 > (size_t)total) {
        fprintf(stderr, "%s: truncated code section\n", path);
        return false;
    }
    *code_out = buf + pos;
    *code_size_out = code_len;
    pos += code_len;

    uint16_t string_count = read_u16le(buf + pos);
    pos += 2;

    char **strings = malloc(sizeof(char *) * (string_count ? string_count : 1));
    for (uint16_t i = 0; i < string_count; i++) {
        if (pos + 2 > (size_t)total) {
            fprintf(stderr, "%s: truncated string table at entry %u\n", path, i);
            return false;
        }
        uint16_t len = read_u16le(buf + pos);
        pos += 2;
        /* +1: each string carries a trailing NUL in the container (see
         * vnasm.py's to_chunk_bytes) that isn't counted in len. */
        if (pos + len + 1 > (size_t)total) {
            fprintf(stderr, "%s: truncated string data at entry %u\n", path, i);
            return false;
        }
        char *s = malloc(len + 1);
        memcpy(s, buf + pos, len);
        s[len] = '\0';
        strings[i] = s;
        pos += len + 1;
    }

    vnb_strings = strings;
    vnb_string_count = string_count;

    printf("loaded %s: %u bytes code, %u strings\n", path, code_len, string_count);
    return true;
}

int main(int argc, char **argv)
{
    const char *vnb_path = NULL;
    uint32_t    start_pc = 0;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--trace") == 0) {
            opt_trace = true;
        } else if (strncmp(argv[i], "--choices=", 10) == 0) {
            parse_choices(argv[i] + 10);
        } else if (strncmp(argv[i], "--vnb=", 6) == 0) {
            vnb_path = argv[i] + 6;
        } else if (strncmp(argv[i], "--pc=", 5) == 0) {
            start_pc = (uint32_t)strtoul(argv[i] + 5, NULL, 0);
        } else {
            fprintf(stderr, "unknown option: %s\n", argv[i]);
            return 2;
        }
    }

    const uint8_t *run_code = demo_code;
    size_t run_code_size = demo_code_size;

    if (vnb_path != NULL) {
        if (!load_vnb(vnb_path, &run_code, &run_code_size)) {
            return 2;
        }
    }

    vn_vm_t vm;
    vn_init(&vm, run_code, run_code_size, &host);
    vm.pc = start_pc;
    vn_status_t status = vn_run(&vm);

    printf("---\n");
    printf("status : %s\n", vn_status_str(status));
    printf("pc     : %u / %u\n", vm.pc, (unsigned)vm.code_size);
    printf("lines  : %u\n", say_count);
    printf("menus  : %u\n", menu_count);

    /* Anything other than a clean finish is a build failure. */
    return status == VN_FINISHED ? 0 : 1;
}
