/**
 * @file demo.h
 * @brief Milestone 1 placeholder script, generated by tools/gen_demo.py.
 *
 * This exists only to exercise the VM, renderer and input path before the
 * asset pipeline lands. assets.c will replace it with appvar-backed chunks.
 */

#ifndef DEMO_H
#define DEMO_H

#include <stdint.h>

extern const uint8_t demo_code[];
extern const char *const demo_strings[];
extern const unsigned demo_code_size;
extern const unsigned demo_string_count;

#endif /* DEMO_H */
